backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "islands"
    label: "Islands"
    folder: "src/islands"
    create: true
#    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Region"
        name: "region"
        widget: "string"
      - label: "Area"
        name: "area"
        widget: "number"
      - label: "Population"
        name: "population"
        widget: "number"
      - label: "Information"
        name: "information"
        widget: "string"
      - label: "Image"
        name: "image"
        widget: "image"
      - label: "Lat"
        name: "lat"
        widget: "number"
      - label: "Long"
        name: "long"
        widget: "number"
      - label: "Body"
        name: "body"
        widget: "markdown"